# Generated by Django 3.0.6 on 2020-06-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200612_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateField(auto_now=True, verbose_name='Last Login'),
        ),
    ]
