# Generated by Django 3.0.6 on 2020-06-12 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200612_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='address',
            field=models.GenericIPAddressField(validators=[django.core.validators.validate_ipv4_address], verbose_name='IPV4 Address'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='status',
            field=models.BooleanField(verbose_name='Status'),
        ),
    ]
